### ISSUE TITLE
SyntaxError: Unexpected token { in JSON at position 51

### ISSUE THREAD

**Issue by jaimejim** [hedwiggggg/spotify-ripper-web#18]
Seems to be broken. Shame I didn't save the container!!

```
Starting spotify-ripper-web_spotify-ripper-web_1 ... done
Attaching to spotify-ripper-web_spotify-ripper-web_1
spotify-ripper-web_1  | undefined:2
spotify-ripper-web_1  | {"stream":"\n"}
spotify-ripper-web_1  | ^
spotify-ripper-web_1  | 
spotify-ripper-web_1  | SyntaxError: Unexpected token { in JSON at position 51
spotify-ripper-web_1  |     at JSON.parse (<anonymous>)
spotify-ripper-web_1  |     at Writable.write [as _write] (/spotify-ripper-web-backend/app.js:24:31)
spotify-ripper-web_1  |     at doWrite (_stream_writable.js:410:12)
spotify-ripper-web_1  |     at writeOrBuffer (_stream_writable.js:394:5)
spotify-ripper-web_1  |     at Writable.write (_stream_writable.js:294:11)
spotify-ripper-web_1  |     at IncomingMessage.ondata (_stream_readable.js:667:20)
spotify-ripper-web_1  |     at IncomingMessage.emit (events.js:189:13)
spotify-ripper-web_1  |     at IncomingMessage.Readable.read (_stream_readable.js:487:10)
spotify-ripper-web_1  |     at flow (_stream_readable.js:931:34)
spotify-ripper-web_1  |     at resume_ (_stream_readable.js:912:3)
```

**Comment by ascheschleier** [comment]
but how? i had the docker runing for a long time, and it worked fine.  just restarted it with no changes at all and got this error as well!

**Comment by rtda2** [comment]
+1

**Comment by hedwiggggg** [comment]
Sorry, I never get any notifications when people are creating issues. 
Well, that bug is kinda weird and I don't really know, what changed.
But I guess I could create a hotfix by wrapping the JSON.parse in a try / catch.

**Comment by hedwiggggg** [comment]
Could you test this? @ascheschleier @jaimejim 
I don't use this tool anymore.

**Comment by hedwiggggg** [comment]
Closing because of inactivity. Tested it, seems to be working fine again.
