### ISSUE TITLE
Web Interface stays on Pending

### ISSUE THREAD

**Issue by KingEldarion2** [hedwiggggg/spotify-ripper-web#32]
Hi,

I installed the Container based on the installation guide. Sadly when I try to download something the Start Button goes to "Pending" and it will stay that way.

There is also no further output in the Web Interface nor in the Docker logs.

The only issue I can see is during startup in the docker logs:

spotify-ripper-web_1  | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ge9k6g6l/pyspotify/

See full log below

If I open the :81 Port in the Browser it simply states:
"Upgrade Required"

Not sure if this is normal behaviour?

Im running Arch (btw)

Can anyone help on how to resolve this?

Kind regards
KingEldarion

`spotify-ripper-web_1  |     Complete output from command python setup.py egg_info:
spotify-ripper-web_1  |     Couldn't find index page for 'cffi' (maybe misspelled?)
spotify-ripper-web_1  |     No local packages or working download links found for cffi>=1.0.0
spotify-ripper-web_1  |     Traceback (most recent call last):
spotify-ripper-web_1  |       File "<string>", line 1, in <module>
spotify-ripper-web_1  |       File "/tmp/pip-build-7_pb9oex/pyspotify/setup.py", line 46, in <module>
spotify-ripper-web_1  |         'Topic :: Software Development :: Libraries',
spotify-ripper-web_1  |       File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
spotify-ripper-web_1  |         _setup_distribution = dist = klass(attrs)
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
spotify-ripper-web_1  |         self.fetch_build_eggs(attrs['setup_requires'])
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
spotify-ripper-web_1  |         replace_conflicting=True,
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
spotify-ripper-web_1  |         dist = best[req.key] = env.best_match(req, ws, installer)
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
spotify-ripper-web_1  |         return self.obtain(req, installer)
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
spotify-ripper-web_1  |         return installer(requirement)
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
spotify-ripper-web_1  |         return cmd.easy_install(req)
spotify-ripper-web_1  |       File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
spotify-ripper-web_1  |         raise DistutilsError(msg)
spotify-ripper-web_1  |     distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.0.0')
spotify-ripper-web_1  |     
spotify-ripper-web_1  |     ----------------------------------------
spotify-ripper-web_1  | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7_pb9oex/pyspotify/
`

**Comment by CL0SeY** [comment]
I have a fix for this here: https://github.com/hedwiggggg/spotify-ripper-web/pull/37
